name: Update Deployment

on:
  push:
    paths:
      - 'bash-release.sh'

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y

      - name: Run Update Script
        run: |
          chmod +x bash-release.sh
          ./bash-release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}