name: Release Management

on:
  push:
    paths:
      - 'repos.yaml'
  workflow_dispatch:  # Manually triggered

permissions:
  contents: write

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: |
            pip install pyyaml
            pip3 install PyGithub

      - name: Run check_and_trigger.py
        run: python check_and_trigger.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}